### ISSUE TITLE
Getting error when making all

### ISSUE THREAD

**Issue by beginner984** [tobiasrausch/svprops#2]
Sorry how I can solve this error

```
make: *** [src/svprops] Error 1
(/home/fi1d18/.conda/onco) [fi1d18@cyan01 svprops]$ make all
g++ -isystem /home/fi1d18/svprops/svprops/src/htslib/ -pedantic -W -Wall -Wno-unknown-pragmas -fno-strict-aliasing -O3 -fno-tree-vectorize -DNDEBUG -D__STDC_LIMIT_MACROS src/svprops.cpp -o src/svprops -L/home/fi1d18/svprops/svprops/src/htslib/ -L/home/fi1d18/svprops/svprops/src/htslib//lib -lhts -lz -llzma -lbz2 -Wl,-rpath,/home/fi1d18/svprops/svprops/src/htslib/
/usr/bin/ld: cannot find -llzma
collect2: ld returned 1 exit status
make: *** [src/svprops] Error 1
(/home/fi1d18/.conda/onco) [fi1d18@cyan01 svprops]$
```

**Comment by tobiasrausch** [comment]
You need a couple system libraries for svprops such as lzma and boost. If you are using Ubuntu you can install these using:

`apt-get install -y build-essential g++ cmake zlib1g-dev libbz2-dev liblzma-dev libboost-all-dev`

**Comment by beginner984** [comment]
Sorry I am getting this
```

(/home/fi1d18/.conda/onco) [fi1d18@cyan01 svprops]$ apt-get install -y build-essential g++ cmake zlib1g-dev libbz2-dev liblzma-dev libboost-all-dev
-bash: apt-get: command not found
(/home/fi1d18/.conda/onco) [fi1d18@cyan01 svprops]$

```

**Comment by tobiasrausch** [comment]
You need to be root/administrator to install these libraries. Please ask your IT service people.

**Comment by beginner984** [comment]
Thank you

Before asking root to install for me, would I get information like read depth for each sample in the position by delly .vcf files?

**Comment by tobiasrausch** [comment]
The RC genotype field contains the read count for each called SV

**Comment by tobiasrausch** [comment]
But you don't need svprops for that, this is already in the Delly BCF output.

**Comment by beginner984** [comment]
Sorry, before asking admins to install things, does this tool extract information like read depth delly .vcf file?

Thank you for bearing with me

**Comment by beginner984** [comment]
Thank you for bearing with me

I need these columns from called SV



```
> head(sv_data)
     Sample Type CHROM_1    POS_1 CHROM_2     POS_2 Tumor_Varcount Tumor_Depth Normal_Depth Driver
1   CHC018T  BND    chr1   753734    chr8    327403             22          52          101   <NA>
2   CHC018T  BND    chr1   753747    chr8    327385             17          37          104   <NA>

```
But I can not find in google how to extract this information from delly BCF or VCF output

**Comment by tobiasrausch** [comment]
I don't know this format. It's not from delly.

**Comment by RamRS** [comment]
Hello @beginner984 , GitHub issues are not the place to ask for help with highly specific tool usage questions. GitHub issues are for problems in the tool's code or issues with the expected behavior. You have already opened multiple posts on Biostars and Bioinfo SE for this exact question, I'd recommend against spamming tool developers on GitHub.
